tags:
    reloads: reloads
    perfentries: perf
    popup: popup
    error: error
    data:
        regex:
            - '\.data\.value$'
            - '\.data\.nodeValue$'
            - '\.data$'
    history: '(:?^|\.)history(:?\.|$)'
    webkitprop: '\.webkit\w+(\.|$)'
    msprop: '\.ms\w+(\.|$)'
    safprop: '\.saf\w+(\.|$)'
    mozprop: '\.moz\w+(\.|$)'
    elemsrc: '\.src(\.|$)'
    elemonload: '\.onload$'
    location: '(:?^|\.)location(:?\.|$)'
    elemattributes: 'attributes\.\d\.(nodeV|v)alue'
    numberedwindowhandle:
        label: 'window[{0}]'
        regex: '^([0-9]+)$'
    windowlength:
        regex:
            - '^length$'
            - '^\d\.length$'
    contentWindow: contentWindow
    contentDocument: contentDocument
    styleSheets: '^document\.styleSheets'
    activeElement: '^document\.activeElement$'
    readystate: '\.readyState$'
    subframes: '^\d\.\d$'
    elemdims:
        regex:
            - \.clientHeight
            - \.clientWidth
            - \.offsetHeight
            - \.offsetTop
            - \.offsetLeft
            - \.offsetWidth
            - \.offsetHeight
            - \.scrollWidth
            - \.scrollHeight
            - \.visualViewport.height
            - \.visualViewport.width
            - \.naturalHeight
            - \.naturalWidth
            - \.height
            - \.width
            - '\.y$'
    windowdims:
        regex:
            - innerWidth|innerHeight|outerWidth|outerHeight
nomatch: unclassified
